### ISSUE TITLE
UART2 Address

### ISSUE THREAD

**Issue by pauloasherring** [TImada/raspi4_freertos#2]
Hey there! First of all, thanks for this port, this is enabling some real learning processes here :)

Secondly, this is not an issue perse. 
But, because it didn't work out of the box for me, I started code browsing to understand what is going on.
And I found that [here](https://github.com/TImada/raspi4_freertos/blob/c80af62d45903c08d626043925092798e65e995f/FreeRTOS/Demo/CORTEX_A72_64-bit_Raspberrypi4/uart/src/uart.c#L12) you define the base address of the UART2.

However, checking the RPi4's [Periherals Document](https://datasheets.raspberrypi.com/bcm2711/bcm2711-peripherals.pdf), p147, I noticed that the UART2 address is offset by 0x80000000 on the code.

So, what would be the rationale here? Is it supposed to be `0xFE201400` or `0x7E201400`? I know that somehow this is correct, otherwise, people would complain that it is not working =)

Again, thank you so very much for the port.
Kind regards, Paulo.

**Comment by TImada** [comment]
Hi Paulo,

The UART2 address (0x7e201400) on P.147 is a memory address for Legacy Master view. Check the section 1.2.4. "Legacy master addresses" on P.6. You can find a sentence describing "**The peripheral addresses specified in this document are legacy master addresses**".

On the other hand, Ubuntu Linux utilizes ARM view with Low Peripheral mode by default rather than Legacy Master view. In that case, the UART2 address starts at 0xfe201400.

You can find memory mapping between Legacy Master view and ARM view with Low Peripheral mode in Figure 1 on P.5.

**Comment by pauloasherring** [comment]
Hello Takayuki,
Thanks for the prompt answer! That completely makes sense.
After adding `arm_64bit=1` to the `config.txt` file, it worked! Thanks a lot, for sharing here and for the support =D
