### ISSUE TITLE
Build raspi4_freertos on windows

### ISSUE THREAD

**Issue by LabNelson** [TImada/raspi4_freertos#3]
Hi Takayuki,
this is also not an issue.
I want to build this project on Windows (cause we have a simulation and testbench tool (build by windows), running with FreeRTOS on the Zynq board).
I want to use your FreeRTOSRPi4-port to shift this simulation and testbench tool from the Zynq-board to the RPI4 for open source ability.  Unfortunately in the first step I have to use windows to build. In the second step, we imagine a linux build variant.
Do you have some hints, or suggestions to build it with windows?
Kind Regards
Nelson

**Comment by TImada** [comment]
GCC on Windows for AArch64 [1] and xPack Windows Build Tools providing the `make` command [2] may work.
(Unfortunately, I cannot check if they can because I do not have any Windows environment)

[1] https://developer.arm.com/-/media/Files/downloads/gnu-a/9.2-2019.12/binrel/gcc-arm-9.2-2019.12-mingw-w64-i686-aarch64-none-elf.tar.xz
[2] https://xpack.github.io/windows-build-tools/install/

**Comment by LabNelson** [comment]
Ah, I assumed to use the aarch64-none-elf-gcc for windows. I also tried a bit with making but there were a few errors.
Your proposal is fantastic. I used the prebuild u-boot (build by ubuntu) and just build the uart.elf by windows with your recommendations.
Thank you again for your help. It heaped me up to the next level!
